### ISSUE TITLE
Server crash because of ConcurrentModificationException

### ISSUE THREAD

**Issue by skyrising** [senseiwells/ChunkDebug#5]
**General Info**
Mod Version: 1.0.6
Minecraft Version: 1.19.2
List of other mods: fabric-api,, lithium, nochatreports, pca-protocol, quickcarpet, spark, starlight, syncmatica

**To Reproduce**
Unknown

**Crash Report / Lastest Log**
```
Description: Exception in server tick loop

java.util.ConcurrentModificationException
        at java.base/java.util.HashMap$HashIterator.nextNode(HashMap.java:1597)
        at java.base/java.util.HashMap$KeyIterator.next(HashMap.java:1620)
        at chunkdebug.feature.ChunkServerNetworkHandler.lambda$forceUpdateChunkData$2(ChunkServerNetworkHandler.java:154)
        at java.base/java.util.HashMap.forEach(HashMap.java:1421)
        at chunkdebug.feature.ChunkServerNetworkHandler.forceUpdateChunkData(ChunkServerNetworkHandler.java:149)
        at chunkdebug.feature.ChunkServerNetworkHandler.tickUpdate(ChunkServerNetworkHandler.java:197)
        at net.minecraft.server.MinecraftServer.handler$zzb000$onTick(MinecraftServer.java:2264)
        at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java)
        at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:665)
        at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257)
        at java.base/java.lang.Thread.run(Thread.java:833)
```

**Screenshots / Videos**
https://clips.twitch.tv/ElegantLivelyNewtHassanChop-tzKYQQitmpgNGEvi

**Comment by senseiwells** [comment]
This has been fixed, you can find the latest verions [here](https://modrinth.com/mod/chunkdebug/versions).

**Comment by skyrising** [comment]
Still happening with 1.0.7, same crash with different line numbers: ```
java.util.ConcurrentModificationException
        at java.base/java.util.HashMap$HashIterator.nextNode(HashMap.java:1597)
        at java.base/java.util.HashMap$KeyIterator.next(HashMap.java:1620)
        at chunkdebug.feature.ChunkServerNetworkHandler.lambda$forceUpdateChunkData$2(ChunkServerNetworkHandler.java:168)
        at java.base/java.util.HashMap.forEach(HashMap.java:1421)
        at chunkdebug.feature.ChunkServerNetworkHandler.forceUpdateChunkData(ChunkServerNetworkHandler.java:163)
        at chunkdebug.feature.ChunkServerNetworkHandler.tickUpdate(ChunkServerNetworkHandler.java:211)
        at net.minecraft.server.MinecraftServer.handler$zzb000$onTick(MinecraftServer.java:2264)
        at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java)
        at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:665)
        at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257)
        at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by senseiwells** [comment]
I've changed it so it uses a Concurrent set now: 2ef438405b4d843f1c701775086c2455b9844bcb

Honestly I cannot for the life of me figure out why on earth it is throwing a CME.
There are no more off-thread shenanigans, and as far as I can see there is no mutating of the set while iterating over the set.
I suspect it's produced as a result of calling ServerChunkManager#getChunk while iterating the set, but afaik
may only call #updateChunkMap if create = true, I cannot find any other instances which would cause this issue.

Apart from not knowing the cause having it be a concurrent set should resolve the issue.

**Comment by senseiwells** [comment]
After a while of trying to reproduce the bug, I caught it in my IDE.

This has been properly fixed now by no longer calling ServerChunkManager#getChunk, but instead using chunk holders.

I can no longer reproduce the bug.

You can download the latest verion [here](https://modrinth.com/mod/chunkdebug/versions).
